services:
  db:
    image: postgres:latest
    container_name: warehouse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: WarehouseDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: warehouse_cache
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: warehouse_kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Izmena ovde:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    ports:
      - "9092:9092"

volumes:
  postgres_data: