// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseSystem.Infrastructure.Persistence;

#nullable disable

namespace WarehouseSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SkladisteDbContext))]
    [Migration("20260326144317_DodajStanjeZaliha")]
    partial class DodajStanjeZaliha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.Artikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MinimalnaKolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Sifra")
                        .IsUnique();

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.StanjeZaliha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikalId")
                        .HasColumnType("integer");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<int>("LokacijaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PoslednjeAzuriranje")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArtikalId");

                    b.HasIndex("LokacijaId");

                    b.ToTable("StanjeZaliha");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.TransakcijaZaliha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtikalId");

                    b.ToTable("TransakcijeZaliha");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.StanjeZaliha", b =>
                {
                    b.HasOne("WarehouseSystem.Domain.Entities.Artikal", "Artikal")
                        .WithMany("Zalihe")
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseSystem.Domain.Entities.Lokacija", "Lokacija")
                        .WithMany("Zalihe")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Lokacija");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.TransakcijaZaliha", b =>
                {
                    b.HasOne("WarehouseSystem.Domain.Entities.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.Artikal", b =>
                {
                    b.Navigation("Zalihe");
                });

            modelBuilder.Entity("WarehouseSystem.Domain.Entities.Lokacija", b =>
                {
                    b.Navigation("Zalihe");
                });
#pragma warning restore 612, 618
        }
    }
}
